---
images:
  tags:
    db_init: docker.io/openstackhelm/heat:train-ubuntu_bionic
    db_drop: docker.io/openstackhelm/heat:train-ubuntu_bionic
    horizon_db_sync: docker.io/openstackhelm/horizon:train-ubuntu_bionic
    horizon: docker.io/openstackhelm/horizon:train-ubuntu_bionic
...
